"""Add openopus_id to composers

Revision ID: b6c0d95eba26
Revises: d334e3a811d7
Create Date: 2026-02-03 10:15:55.517746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c0d95eba26'
down_revision: Union[str, Sequence[str], None] = 'd334e3a811d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('composers', sa.Column('openopus_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_composers_openopus_id'), 'composers', ['openopus_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_composers_openopus_id'), table_name='composers')
    op.drop_column('composers', 'openopus_id')
    # ### end Alembic commands ###
