"""Add imslp_url to Work

Revision ID: d9d423bacc60
Revises: b6c0d95eba26
Create Date: 2026-02-10 10:07:15.652805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d423bacc60'
down_revision: Union[str, Sequence[str], None] = 'b6c0d95eba26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('imslp_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'imslp_url')
    # ### end Alembic commands ###
