name: Machine Start (daytime)

on:
  schedule:
    - cron: '0 8 * * *'  # 10:00 CEST / 09:00 CET
  workflow_dispatch:

jobs:
  start:
    name: Start Fly machine
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          MACHINE_ID=$(flyctl machine list --app exam-record-beta --json | jq -r '.[0].id')
          flyctl machine start "$MACHINE_ID" --app exam-record-beta
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
